import type { FieldControl, FieldRuleName, FieldValue, FormField } from '@src/core'

export const MATRIX_RULES: readonly FieldRuleName[] = [
	'required',
	'minimum',
	'maximum',
	'step',
	'pattern',
	'email',
	'url',
	'integer',
	'alphanumeric',
]

export const RULE_APPLICABILITY: Readonly<
	Record<FieldControl, Readonly<Record<FieldRuleName, boolean>>>
> = {
	text: {
		required: true,
		minimum: true,
		maximum: true,
		step: false,
		pattern: true,
		email: true,
		url: true,
		integer: true,
		alphanumeric: true,
	},
	editor: {
		required: true,
		minimum: true,
		maximum: true,
		step: false,
		pattern: true,
		email: true,
		url: true,
		integer: true,
		alphanumeric: true,
	},
	password: {
		required: true,
		minimum: true,
		maximum: true,
		step: false,
		pattern: true,
		email: true,
		url: true,
		integer: true,
		alphanumeric: true,
	},
	number: {
		required: true,
		minimum: true,
		maximum: true,
		step: true,
		pattern: false,
		email: false,
		url: false,
		integer: true,
		alphanumeric: false,
	},
	date: {
		required: true,
		minimum: true,
		maximum: true,
		step: false,
		pattern: true,
		email: true,
		url: true,
		integer: true,
		alphanumeric: true,
	},
	time: {
		required: true,
		minimum: true,
		maximum: true,
		step: false,
		pattern: true,
		email: true,
		url: true,
		integer: true,
		alphanumeric: true,
	},
	datetime: {
		required: true,
		minimum: true,
		maximum: true,
		step: false,
		pattern: true,
		email: true,
		url: true,
		integer: true,
		alphanumeric: true,
	},
	color: {
		required: true,
		minimum: false,
		maximum: false,
		step: false,
		pattern: true,
		email: true,
		url: true,
		integer: true,
		alphanumeric: true,
	},
	confirm: {
		required: true,
		minimum: false,
		maximum: false,
		step: false,
		pattern: false,
		email: false,
		url: false,
		integer: false,
		alphanumeric: false,
	},
	select: {
		required: true,
		minimum: false,
		maximum: false,
		step: false,
		pattern: true,
		email: true,
		url: true,
		integer: true,
		alphanumeric: true,
	},
	checkbox: {
		required: true,
		minimum: true,
		maximum: true,
		step: false,
		pattern: false,
		email: false,
		url: false,
		integer: false,
		alphanumeric: false,
	},
	file: {
		required: true,
		minimum: true,
		maximum: true,
		step: false,
		pattern: false,
		email: false,
		url: false,
		integer: false,
		alphanumeric: false,
	},
}

export const MATRIX_FIELDS: Readonly<Record<FieldControl, FormField>> = {
	text: { control: 'text', name: 'text' },
	editor: { control: 'editor', name: 'editor' },
	password: { control: 'password', name: 'password' },
	number: { control: 'number', name: 'number' },
	date: { control: 'date', name: 'date' },
	time: { control: 'time', name: 'time' },
	datetime: { control: 'datetime', name: 'datetime' },
	color: { control: 'color', name: 'color' },
	confirm: { control: 'confirm', name: 'confirm' },
	select: {
		control: 'select',
		name: 'select',
		choices: [{ value: 'choice', label: 'Choice' }],
	},
	checkbox: {
		control: 'checkbox',
		name: 'checkbox',
		choices: [
			{ value: 'one', label: 'One' },
			{ value: 'two', label: 'Two' },
		],
	},
	file: { control: 'file', name: 'file', multiple: true },
}

export const MATRIX_VALUES: Readonly<Record<FieldControl, FieldValue>> = {
	text: 'text',
	editor: 'editor',
	password: 'password',
	number: 2,
	date: '2026-08-15',
	time: '09:30',
	datetime: '2026-08-15T09:30',
	color: '#336699',
	confirm: true,
	select: 'choice',
	checkbox: ['one'],
	file: ['one.txt'],
}
